spring:
  datasource:
    url: jdbc:mysql://localhost:3306/researchteam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678sx.
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: none

mybatis:
  type-aliases-package: com.chongan.pojo
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=contSql

server:
  port: 80


